home task 9+10
msantipova/qa-automation-java pull request #10
Opened 2021-09-07 17:46 UTC by msantipova

(9)save response in ArrayResponse
(9)add operation change status
(10)add exception handling

2021-09-13 07:33 UTC, VasilevPoul requested changes

2021-09-13 07:33 UTC, VasilevPoul commented on pom.xml
> +                    <target>7</target>
16 и 17 строка, для использования лямбда выражений(это те которые в assertAll у тебя) надо задать 8 и более

2021-09-13 07:33 UTC, VasilevPoul commented on src/main/java/com/tinkoff/edu/app/ArrayResponse.java
> +        }
Данная форма цикла for устарела, и если тебе не нужен индекс то используй следующий формат:
```
        for (LoanResponse response : responses) {
            if (response.getRequestId().equals(id)) {
                break;
            }
        }
```

Проверь по всему проекту

2021-09-13 07:33 UTC, VasilevPoul commented on src/main/java/com/tinkoff/edu/app/ArrayResponse.java
> +        }
Вцелом в этой функции тебе надо прямо в цикле делать return вместо break, а после тела цикла можно прокидывать ошибку т.к. за весь цикл не удалось обнаружить записи с нужным UUID

2021-09-13 07:33 UTC, VasilevPoul commented on src/main/java/com/tinkoff/edu/app/ArrayResponse.java
> +        System.out.println( "ArrayResponse {" + responses[counter].getRequestId()
Используй printf вместо println
` System.out.println("value: %s and %s", 500, "AAA");`
напишет в консоль:
`value: 500 and AAA`

а при формировании строки всегда вместо '+' используй:
`String.format("value: %s and %s", 500, "AAA")`

2021-09-13 07:33 UTC, VasilevPoul commented on src/main/java/com/tinkoff/edu/app/LoanResponse.java
> +                responseType == that.responseType &&
Почему ты в 44 строке не используешь Objects.equals ?

2021-09-23 08:09 UTC, msantipova commented
исправлено

2021-09-23 08:17 UTC, VasilevPoul approved these changes

2021-09-23 08:18 UTC, merged