home task 4 create classes from credit Request
msantipova/qa-automation-java pull request #5
Opened 2021-08-17 13:10 UTC by msantipova

2021-08-17 13:44 UTC, VasilevPoul commented
По codeStyle:

2021-08-17 13:51 UTC, VasilevPoul requested changes
По codeStyle:

class TheClass {
// пустая строка
    String variable;
    Integer anotherVariable;
// пустая строка
    public void function(String arg) {
        //  Do something
    }
// пустая строка
    public void anotherFunction(String arg) {
        //  Do something
    }
// пустая строка
}
// пустая строка
Проследи что бы твои классы соответствовали примеру выше,
Плюс пробелы внутри строк всегда можно исправить сочетанием: Ctrl + Alt + L
Так же необходимо убирать все неиспользуемые импорты в классах сочетанием: Ctrl + Alt + O

2021-08-17 13:51 UTC, VasilevPoul commented on src/main/java/com/tinkoff/edu/test/LoanCalcTest.java
> +        int reguestId = LoanCalcController.createRequest();
Опечатка, замени плз re**g**uestId ->  re**q**uestId

2021-08-17 15:40 UTC, msantipova commented on src/main/java/com/tinkoff/edu/test/LoanCalcTest.java
> +        int reguestId = LoanCalcController.createRequest();
исправлено

2021-08-18 05:59 UTC, VasilevPoul commented on src/main/java/com/tinkoff/edu/test/LoanCalcTest.java
> +        int reguestId = LoanCalcController.createRequest();
Отличная работа! Можно мержить.

2021-08-18 05:59 UTC, VasilevPoul approved these changes

2021-08-18 06:01 UTC, VasilevPoul approved these changes

2021-08-18 07:29 UTC, merged