Home task/six
msantipova/qa-automation-java pull request #7
Opened 2021-08-23 19:45 UTC by msantipova

отпочковала ветку прежде, чем смержила, и от задания 5, все еще изучаю гит
статическую переменную оставила, в ней мы как раз пока храним и инкрементим ИД заявки, потому она статическая у нас по проекту
сделала наглядный циклик с рандомом, дабы углядеть, что он там меняется

2021-08-25 07:27 UTC, VasilevPoul requested changes

2021-08-25 07:27 UTC, VasilevPoul commented on src/main/java/com/tinkoff/edu/app/LoanCalcController.java
> +    private LoanService repo;
Эта переменная не репозиторий, попробуй переименовать на что-то более соответствующее.

2021-08-25 07:27 UTC, VasilevPoul commented on src/main/java/com/tinkoff/edu/app/LoanCalcController.java
> +    public LoanCalcController(LoanService Srepo) {
Тут тоже самое(надо переименовать), плюс наименование переменных начинается с lowercase

2021-08-25 07:27 UTC, VasilevPoul commented on src/main/java/com/tinkoff/edu/app/LoanCalcService.java
> +    public LoanResponse createRequest(LoanRequest request) {
Тут тоже стоит переименовать наименование функции, предлагаю оставить только **create**, 
потому что сейчас звучит так что функция создаёт какой-то запрос а не запрашивает создание

2021-08-26 12:21 UTC, msantipova commented
исправлено

2021-08-26 12:54 UTC, VasilevPoul approved these changes

2021-08-26 13:00 UTC, merged