Home task/eight
msantipova/qa-automation-java pull request #9
Opened 2021-09-01 12:00 UTC by msantipova

2021-09-02 07:03 UTC, VasilevPoul requested changes
IPLoanCalcService, OOOLoanCalcService, PersonLoanCalcService

2021-09-02 07:03 UTC, VasilevPoul commented on .gitignore
> +!/target/site/jacoco/index.html
Во первых gitLab подсказывает что надо добавить пустую строку после последней
Во вторых зачем тебе в репозитории результаты запуска автотестов? Эта информация не должна храниться в репозитории.

2021-09-02 07:03 UTC, VasilevPoul commented on pom.xml
>  </project>
Требуется пустая строка после последней

2021-09-02 07:03 UTC, VasilevPoul commented on src/main/java/com/tinkoff/edu/app/IPLoanCalcService.java
> +    private LoanCalcRepository repo;
Добавь пустую строку  после 6

2021-09-02 07:03 UTC, VasilevPoul commented on src/main/java/com/tinkoff/edu/app/IPLoanCalcService.java
> +    private LoanCalcRepository repo;
IDEA подсказывает что данную переменную следует сделать final, так как ты задаёшь ей значение только один раз и в конструкторе

2021-09-02 07:03 UTC, VasilevPoul commented on src/main/java/com/tinkoff/edu/app/LoanCalcController.java
> +
Данная конструкция плохо читается

1. По правилам хорошего тона после if всегда пиши обработку в `{}` даже если это одна строка.
2. Тут вообще по хорошему надо использовать `switch` загугли как он работает, если будет непонятно то подскажу.

2021-09-02 07:03 UTC, VasilevPoul commented on src/main/java/com/tinkoff/edu/app/OOOLoanCalcService.java
>      private LoanCalcRepository repo;
Требуется пустая строка после 6

2021-09-02 07:03 UTC, VasilevPoul commented on src/main/java/com/tinkoff/edu/app/OOOLoanCalcService.java
> +        if ((request.getAmount() > 10000) & (request.getMonths() < 12))
Используй исключающее или `&&`

2021-09-02 07:03 UTC, VasilevPoul commented on src/main/java/com/tinkoff/edu/app/PersonLoanCalcService.java
> +    private LoanCalcRepository repo;
Добавь пустую строку после 6

2021-09-03 07:38 UTC, msantipova commented
исправлено

2021-09-03 08:35 UTC, VasilevPoul approved these changes

2021-09-03 08:40 UTC, merged